### ISSUE TITLE
New spark firmware upgrade

### ISSUE THREAD

**Issue by Ziozanna** [richtamblyn/PGSparkLite-Pedal#11]
In june 2021 Positive Grid released the firmware 1.4.3.174 which adds 3 new pedals and 3 new amps.

I'm intesivelly run  PGSparkLite-Pedal with lot of satifaction and despite the risk of incompatibility of the new firmware i decided to upgrade.

Fortunatelly or thanks to the good written software the pedalboard still running flawlessly untin I do not set the new pedals or amps thrug the app and save it on HW on spark.

At the moment in which I recall the setting via pedalbord the web interface crashes, becomes white with an error message.

There is only one way to retrive this situation ie Spark factory reset.

I would like to contribute adding new amps and pedals and also create a setting for scenes but the software withoud documentation is really criptical for me.

Can I ask if it possible to accomodate the software for the ne fw or have some docs to make the job an release it for the community?

**Comment by richtamblyn** [comment]
Hi Ziozanna,
Thanks for your message, I've begun work on adding the new Amps and Pedals to the configuration. As soon as I have a test branch available I'll let you know if you'd be willing help me with testing?

**Comment by richtamblyn** [comment]
Hi Ziozanna,

Implementing the new amps and pedals took less effort than anticipated. If you pull the latest PGSparkLite master branch this should stop your amp crashes.

Kind regards,
Rich
