### ISSUE TITLE
Connect BT device in parallel with pedal

### ISSUE THREAD

**Issue by Ziozanna** [richtamblyn/PGSparkLite-Pedal#6]
Good morning teams

great project.

As in the object when the pedal is connectes the Audio BT interface is locked so I cannt play backing track.

It just works with USB cable. 

Is this a bug or a normal behavior ?

Zanna

**Comment by richtamblyn** [comment]
Hi Zanna,
The pedal replaces the official Positive Grid Mobile App and so this behaviour is expected.
